# This workflow runs edgetest on edgetest @ 17:35 UTC Fridays.
# https://github.com/edgetest-dev/run-edgetest-action

name: Run edgetest
on:
  schedule:
    - cron: '35 17 * * 5'
jobs:
  edgetest:
    runs-on: ubuntu-latest
    name: running edgetest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - id: run-edgetest
        uses: edgetest-dev/run-edgetest-action@v1.4
        with:
          edgetest-flags: '-c pyproject.toml --export'
          base-branch: 'dev'
          skip-pr: 'false'
