# This workflow runs edgetest on edgetest @ 17:35 UTC Fridays.
# https://github.com/edgetest-dev/run-edgetest-action

name: Run edgetest
on:
  schedule:
    - cron: '35 17 * * 5'
jobs:
  edgetest:
    runs-on: ubuntu-24.04
    name: running edgetest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v7.0.1
        with:
          ref: main
      - id: run-edgetest
        uses: edgetest-dev/run-edgetest-action@8ceeac94abe951d6b51305454bc6d0ff2096e2ec # pin@v1.7
        with:
          edgetest-flags: '-c pyproject.toml --export'
          base-branch: 'main'
          skip-pr: 'false'
          add-paths: 'pyproject.toml, uv.lock'
