# Install and test
name: Python package

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                python-version:
                    - "3.10"
                    - "3.11"
                    - "3.12"
                    - "3.13"
        steps:
            - uses: actions/checkout@v4
            - name: Install uv and set the Python version
              uses: astral-sh/setup-uv@v7
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: uv sync --locked --all-extras --dev
            - name: Run ruff QA checks
              run: uv run ruff check .
            - name: Check formatting
              run: uv run ruff format . --check
            - name: Check static typing
              run: uv run mypy edgetest
            - name: Run unit testing
              run: uv run python -m pytest tests --cov=edgetest --cov-fail-under=90
